"""
S.Y.N. Brain — Command Dispatcher
==================================
The central nervous system of S.Y.N.
Takes the parsed IntentResult, looks up the corresponding executor in the
ModuleRegistry, calls the function with extracted entities, and manages
fallback generation using the LLM Brain when query triggers conversational fallback.

DESIGN PATTERNS:
1. Dispatcher Pattern: Routes events/results to specific worker handlers.
2. Error Boundary: Wraps module execution in try-except statements to guarantee 
   graceful degradation (e.g., calling the LLM brain if a handler crashes).
"""

from typing import Dict, Any, Generator
from backend.utils.logger import get_logger
from backend.brain.intent_router import IntentResult
from backend.brain.module_registry import get_handler
from backend.brain.llm_engine import LLMEngine

logger = get_logger("DISPATCHER")


class Dispatcher:
    """
    Orchestrates execution of commands. Links parsing intents to functional routines,
    and falls back to conversational processing when needed.
    """

    def __init__(self):
        self.llm = LLMEngine()

    def dispatch(self, result: IntentResult) -> str:
        """
        Receives an IntentResult, routes to the appropriate module handler,
        or calls the conversational LLM core.
        
        Rules:
        1. If confidence is >= 0.6 and we have a registered handler, run it.
        2. If confidence is low or the intent is 'chat', run the LLM.
        3. If execution fails, gracefully log and default to LLM.
        """
        intent = result.intent
        confidence = result.confidence
        entities = result.entities
        query = result.raw_query
        
        logger.info(f"Dispatching intent: '{intent}' (Confidence: {confidence})")
        
        # 1. LLM Chat Fallback (Low confidence or explicit 'chat' intent)
        if intent == "chat" or confidence < 0.6:
            logger.info(f"Query '{query}' routed to LLM conversational brain.")
            return self.llm.generate(query)
            
        # 2. Command Module Execution
        handler = get_handler(intent)
        if handler:
            try:
                logger.debug(f"Invoking handler for intent '{intent}' with entities: {entities}")
                response = handler(entities)
                logger.info(f"Handler execution successful. Result: '{response}'")
                return response
            except Exception as e:
                logger.error(f"Handler for intent '{intent}' crashed with error: {e}", exc_info=True)
                logger.warning("Routing query to LLM fallback due to handler exception.")
                # If execution crashes, fallback to LLM so the user gets an answer
                return self.llm.generate(query)
        else:
            # 3. Missing Handler Fallback (Should rarely occur if intents match registry)
            logger.warning(f"No handler registered for intent '{intent}'. Routing to LLM.")
            return self.llm.generate(query)

    def dispatch_stream(self, result: IntentResult) -> Generator[str, None, None]:
        """
        Streaming version of dispatch.
        Yields chunks of the response as they are generated by the LLM, or the
        complete output of a mock/real action executor at once.
        """
        intent = result.intent
        confidence = result.confidence
        entities = result.entities
        query = result.raw_query
        
        logger.info(f"Streaming dispatch for intent: '{intent}' (Confidence: {confidence})")
        
        # 1. LLM Chat Fallback (Low confidence or 'chat' intent)
        if intent == "chat" or confidence < 0.6:
            logger.info(f"Query '{query}' routed to LLM streaming brain.")
            yield from self.llm.generate_stream(query)
            return
            
        # 2. Command Module Execution (Mock handlers are single-shot strings)
        handler = get_handler(intent)
        if handler:
            try:
                logger.debug(f"Invoking handler for intent '{intent}' with entities: {entities}")
                response = handler(entities)
                logger.info(f"Handler execution successful. Result: '{response}'")
                yield response
            except Exception as e:
                logger.error(f"Handler for intent '{intent}' crashed: {e}", exc_info=True)
                logger.warning("Routing query to LLM streaming fallback due to handler exception.")
                yield from self.llm.generate_stream(query)
        else:
            logger.warning(f"No handler registered for intent '{intent}'. Routing to LLM.")
            yield from self.llm.generate_stream(query)
